; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.18"

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[email_ajax_check][download][type] = ""
projects[email_ajax_check][download][url] = ""
projects[email_ajax_check][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[gb][download][type] = ""
projects[gb][download][url] = ""
projects[gb][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[query_test][download][type] = ""
projects[query_test][download][url] = ""
projects[query_test][type] = "module"

